version: '3.8'

services:
  pong-server:
    name: pong-server
    build: ./server
    ports:
      - "4100:3000"
      
  pong-client:
    name: pong-client
    build: ./client
    ports:
      - "3300:3000"
    depends_on:
      - pong-server
